# Generated by Django 4.2.2 on 2024-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="citizenship_rf",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Гражданство РФ"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_born",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
