# Generated by Django 4.2.2 on 2024-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_address_alter_user_citizenship_rf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен"
            ),
        ),
    ]
