# Generated by Django 4.2.2 on 2024-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место рождения",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="candidates/photos/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "official_website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Официальный сайт"
                    ),
                ),
                (
                    "social_media_links",
                    models.TextField(
                        blank=True, null=True, verbose_name="Социальные сети"
                    ),
                ),
                (
                    "universities",
                    models.TextField(
                        blank=True, null=True, verbose_name="Университеты"
                    ),
                ),
                (
                    "degrees",
                    models.TextField(blank=True, null=True, verbose_name="Степени"),
                ),
                (
                    "work_experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Рабочие места"
                    ),
                ),
                (
                    "political_experience",
                    models.TextField(
                        blank=True, null=True, verbose_name="Опыт в политике"
                    ),
                ),
                (
                    "goals_and_objectives",
                    models.TextField(
                        blank=True, null=True, verbose_name="Цели и задачи"
                    ),
                ),
                (
                    "projects_and_initiatives",
                    models.TextField(
                        blank=True, null=True, verbose_name="Проекты и инициативы"
                    ),
                ),
                (
                    "awards_and_recognitions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Награды и признания"
                    ),
                ),
                (
                    "key_achievements",
                    models.TextField(
                        blank=True, null=True, verbose_name="Основные достижения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат",
                "verbose_name_plural": "Кандидаты",
            },
        ),
    ]
